# Generated by Django 4.2.7 on 2026-02-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
    ]
