# Generated by Django 4.2.7 on 2026-02-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_document_created_at_alter_document_chunk_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='chunk_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
