# Generated by Django 4.2.7 on 2026-02-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_alter_document_chunk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='course_id',
            field=models.IntegerField(default=401),
        ),
    ]
