# Generated by Django 4.2.7 on 2026-02-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='course',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
