# Generated by Django 4.2.7 on 2026-02-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='course',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='General Chat', max_length=200),
        ),
    ]
